---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-resend-smtp
  namespace: monitoring
spec:
  encryptedData:
    password: AgBWi2VaFe9H7iQlWp3PFf+PZ5y0Bj3XnN5pAlTY5M+vIvtPlMq8v0BbQP6TfVngQInO5pSUsCj8RmzY6pUxa/NEt2UIgRABDj/bERtXtQ2fi3gOG9Hbjzjlb6wyQ5m5cFt/vO/m97mKfb8gu+YSCx31RxihLihPHfPVPQf7o5nF/CXJm2bcoZzEBDDJSS1ot/b9NASQw1TV+guMJ7j2cyZT53sh6Pe9PIUbxxn6cPZPZ2/AuJR3KdPzySv/f23TRgu+xuHH+BTQWVXmYw48fpfkXwNWCfo5AWiBCFdkAwx8pebtJT8ktUjcH060CdlkNOYw+U5kdWO//YD21vGf6fIuVXZbk5rURk9BbcGGjZUDk5GEuVyhoIdw/oGDx1RTc+UILQ65f63Iiev0npZmLEJ0fmaTit9xgIoTQOpJ/vTKzWk0618fKKN3jrl76OJPar1Q1L/pYNEoXdnFl36k0QV1ng4qvFpCIYpu8tavIuBOXBdY85VWzn2gLdbvoW5mhcR+dqNNwjfNR8yF58k53y3nGRzYwVquiwV04YVp9nQdR8PfYJrglF9v+JdTHScp18eWFeLTYn6si4egVY9PVfLxWPQcefFG30xwy5D79+gWeAOpjluwkdAzNr3EUCAfvgJ1YjGGwdILG6agdIXGZBTMSPQYPzORHYdswtR3N0yHsCNoP1OGGlEH+IXj2CZWoLCEXelUwvpXPk2TIIpcWgs2cYhKe3ClkB/34lytrd5DyflmDjQ=
  template:
    metadata:
      name: alertmanager-resend-smtp
      namespace: monitoring
