sonar.projectKey=BIRAJ49_OpsForge
sonar.organization=biraj49
sonar.projectName=OpsForge
sonar.sourceEncoding=UTF-8

sonar.sources=backend/app,frontend/src
sonar.tests=backend/app/tests,frontend/tests
sonar.exclusions=backend/app/tests/**,frontend/src/assets/**,frontend/src/data/mockData.js
sonar.test.inclusions=backend/app/tests/**/*.py,frontend/tests/**/*.test.js

sonar.python.version=3.12
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
