from sqlalchemy import delete
from sqlalchemy.orm import Session

from app.core.config import settings
from app.models.generated_file import GeneratedFile
from app.models.project import Project


def _image(project: Project, tag: str = "latest", github_username: str | None = None) -> str:
    owner = github_username or settings.GHCR_USERNAME
    return f"ghcr.io/{owner}/{project.name}:{tag}"


def build_files(project: Project, github_username: str | None = None) -> list[dict[str, str]]:
    owner = github_username or settings.GITHUB_USERNAME
    image = _image(project, github_username=github_username)
    app_name = project.name
    namespace = project.namespace
    return [
        {"file_name": "Dockerfile.frontend", "file_path": "frontend/Dockerfile", "file_type": "docker", "content": "FROM node:22-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci\nCOPY . .\nRUN npm run build\nFROM nginx:1.27-alpine\nCOPY --from=0 /app/dist /usr/share/nginx/html\n"},
        {"file_name": "Dockerfile.backend", "file_path": "backend/Dockerfile", "file_type": "docker", "content": "FROM python:3.12-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\nCMD [\"uvicorn\", \"app.main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]\n"},
        {"file_name": "docker-compose.yml", "file_path": "docker-compose.yml", "file_type": "compose", "content": "services:\n  backend:\n    build: ./backend\n    environment:\n      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/app\n  frontend:\n    build: ./frontend\n  postgres:\n    image: postgres:16\n    environment:\n      POSTGRES_PASSWORD: postgres\n  redis:\n    image: redis:7-alpine\n"},
        {"file_name": ".env.example", "file_path": ".env.example", "file_type": "env", "content": "DATABASE_URL=postgresql://postgres:postgres@postgres:5432/app\nREDIS_URL=redis://redis:6379/0\nSECRET_KEY=replace-with-secure-value\n"},
        {"file_name": "namespace.yaml", "file_path": "k8s/namespace.yaml", "file_type": "kubernetes", "content": f"apiVersion: v1\nkind: Namespace\nmetadata:\n  name: {namespace}\n"},
        {"file_name": "frontend-deployment.yaml", "file_path": "k8s/frontend-deployment.yaml", "file_type": "kubernetes", "content": f"apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: {app_name}-frontend\n  namespace: {namespace}\nspec:\n  replicas: 2\n  selector:\n    matchLabels:\n      app: {app_name}-frontend\n  template:\n    metadata:\n      labels:\n        app: {app_name}-frontend\n    spec:\n      containers:\n        - name: frontend\n          image: {image}\n          ports:\n            - containerPort: 80\n"},
        {"file_name": "frontend-service.yaml", "file_path": "k8s/frontend-service.yaml", "file_type": "kubernetes", "content": f"apiVersion: v1\nkind: Service\nmetadata:\n  name: {app_name}-frontend\n  namespace: {namespace}\nspec:\n  selector:\n    app: {app_name}-frontend\n  ports:\n    - port: 80\n      targetPort: 80\n"},
        {"file_name": "backend-deployment.yaml", "file_path": "k8s/backend-deployment.yaml", "file_type": "kubernetes", "content": f"apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: {app_name}-backend\n  namespace: {namespace}\nspec:\n  replicas: 2\n  selector:\n    matchLabels:\n      app: {app_name}-backend\n  template:\n    metadata:\n      labels:\n        app: {app_name}-backend\n    spec:\n      containers:\n        - name: backend\n          image: {image}\n          envFrom:\n            - secretRef:\n                name: {app_name}-secret\n            - configMapRef:\n                name: {app_name}-config\n          ports:\n            - containerPort: 8000\n"},
        {"file_name": "backend-service.yaml", "file_path": "k8s/backend-service.yaml", "file_type": "kubernetes", "content": f"apiVersion: v1\nkind: Service\nmetadata:\n  name: {app_name}-backend\n  namespace: {namespace}\nspec:\n  selector:\n    app: {app_name}-backend\n  ports:\n    - port: 8000\n      targetPort: 8000\n"},
        {"file_name": "postgres-statefulset.yaml", "file_path": "k8s/postgres-statefulset.yaml", "file_type": "kubernetes", "content": f"apiVersion: apps/v1\nkind: StatefulSet\nmetadata:\n  name: {app_name}-postgres\n  namespace: {namespace}\nspec:\n  serviceName: {app_name}-postgres\n  replicas: 1\n  selector:\n    matchLabels:\n      app: {app_name}-postgres\n  template:\n    metadata:\n      labels:\n        app: {app_name}-postgres\n    spec:\n      containers:\n        - name: postgres\n          image: postgres:16\n          env:\n            - name: POSTGRES_PASSWORD\n              valueFrom:\n                secretKeyRef:\n                  name: {app_name}-secret\n                  key: POSTGRES_PASSWORD\n"},
        {"file_name": "postgres-service.yaml", "file_path": "k8s/postgres-service.yaml", "file_type": "kubernetes", "content": f"apiVersion: v1\nkind: Service\nmetadata:\n  name: {app_name}-postgres\n  namespace: {namespace}\nspec:\n  selector:\n    app: {app_name}-postgres\n  ports:\n    - port: 5432\n"},
        {"file_name": "redis-deployment.yaml", "file_path": "k8s/redis-deployment.yaml", "file_type": "kubernetes", "content": f"apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: {app_name}-redis\n  namespace: {namespace}\nspec:\n  replicas: 1\n  selector:\n    matchLabels:\n      app: {app_name}-redis\n  template:\n    metadata:\n      labels:\n        app: {app_name}-redis\n    spec:\n      containers:\n        - name: redis\n          image: redis:7-alpine\n"},
        {"file_name": "redis-service.yaml", "file_path": "k8s/redis-service.yaml", "file_type": "kubernetes", "content": f"apiVersion: v1\nkind: Service\nmetadata:\n  name: {app_name}-redis\n  namespace: {namespace}\nspec:\n  selector:\n    app: {app_name}-redis\n  ports:\n    - port: 6379\n"},
        {"file_name": "ingress.yaml", "file_path": "k8s/ingress.yaml", "file_type": "kubernetes", "content": f"apiVersion: networking.k8s.io/v1\nkind: Ingress\nmetadata:\n  name: {app_name}\n  namespace: {namespace}\nspec:\n  ingressClassName: nginx\n  rules:\n    - host: {app_name}.local\n      http:\n        paths:\n          - path: /\n            pathType: Prefix\n            backend:\n              service:\n                name: {app_name}-frontend\n                port:\n                  number: 80\n"},
        {"file_name": "configmap.yaml", "file_path": "k8s/configmap.yaml", "file_type": "kubernetes", "content": f"apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: {app_name}-config\n  namespace: {namespace}\ndata:\n  APP_ENV: production\n  REDIS_URL: redis://{app_name}-redis:6379/0\n"},
        {"file_name": "secret.yaml", "file_path": "k8s/secret.yaml", "file_type": "kubernetes", "content": f"apiVersion: v1\nkind: Secret\nmetadata:\n  name: {app_name}-secret\n  namespace: {namespace}\ntype: Opaque\nstringData:\n  DATABASE_URL: \"replace-with-database-url\"\n  POSTGRES_PASSWORD: \"replace-with-secure-password\"\n  JWT_SECRET_KEY: \"replace-with-secure-secret\"\n"},
        {"file_name": "hpa.yaml", "file_path": "k8s/hpa.yaml", "file_type": "kubernetes", "content": f"apiVersion: autoscaling/v2\nkind: HorizontalPodAutoscaler\nmetadata:\n  name: {app_name}-backend\n  namespace: {namespace}\nspec:\n  scaleTargetRef:\n    apiVersion: apps/v1\n    kind: Deployment\n    name: {app_name}-backend\n  minReplicas: 2\n  maxReplicas: 8\n  metrics:\n    - type: Resource\n      resource:\n        name: cpu\n        target:\n          type: Utilization\n          averageUtilization: 70\n"},
        {"file_name": "Chart.yaml", "file_path": "helm/Chart.yaml", "file_type": "helm", "content": f"apiVersion: v2\nname: {app_name}\ndescription: OpsForge generated chart\nversion: 0.1.0\nappVersion: 0.1.0\n"},
        {"file_name": "values.yaml", "file_path": "helm/values.yaml", "file_type": "helm", "content": f"image:\n  repository: ghcr.io/{owner}/{app_name}\n  tag: latest\nnamespace: {namespace}\nreplicaCount: 2\nsecrets:\n  DATABASE_URL: replace-with-database-url\n"},
        {"file_name": "templates/deployment.yaml", "file_path": "helm/templates/deployment.yaml", "file_type": "helm", "content": "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: {{ .Chart.Name }}\nspec:\n  replicas: {{ .Values.replicaCount }}\n  selector:\n    matchLabels:\n      app: {{ .Chart.Name }}\n  template:\n    metadata:\n      labels:\n        app: {{ .Chart.Name }}\n    spec:\n      containers:\n        - name: app\n          image: \"{{ .Values.image.repository }}:{{ .Values.image.tag }}\"\n"},
        {"file_name": "templates/service.yaml", "file_path": "helm/templates/service.yaml", "file_type": "helm", "content": "apiVersion: v1\nkind: Service\nmetadata:\n  name: {{ .Chart.Name }}\nspec:\n  ports:\n    - port: 80\n      targetPort: 8000\n"},
        {"file_name": "templates/ingress.yaml", "file_path": "helm/templates/ingress.yaml", "file_type": "helm", "content": "apiVersion: networking.k8s.io/v1\nkind: Ingress\nmetadata:\n  name: {{ .Chart.Name }}\nspec:\n  ingressClassName: nginx\n"},
        {"file_name": "templates/configmap.yaml", "file_path": "helm/templates/configmap.yaml", "file_type": "helm", "content": "apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: {{ .Chart.Name }}-config\ndata:\n  APP_ENV: production\n"},
        {"file_name": "templates/secret.yaml", "file_path": "helm/templates/secret.yaml", "file_type": "helm", "content": "apiVersion: v1\nkind: Secret\nmetadata:\n  name: {{ .Chart.Name }}-secret\nstringData:\n  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}\n"},
        {"file_name": "templates/hpa.yaml", "file_path": "helm/templates/hpa.yaml", "file_type": "helm", "content": "apiVersion: autoscaling/v2\nkind: HorizontalPodAutoscaler\nmetadata:\n  name: {{ .Chart.Name }}\nspec:\n  minReplicas: 2\n  maxReplicas: 8\n"},
        {"file_name": "ci-cd.yml", "file_path": ".github/workflows/ci-cd.yml", "file_type": "github_actions", "content": f"name: OpsForge CI/CD\non:\n  push:\n    branches: [main]\njobs:\n  validate-generated-devops:\n    runs-on: ubuntu-latest\n    permissions:\n      contents: read\n      packages: write\n    steps:\n      - uses: actions/checkout@v4\n      - name: Validate generated files\n        run: |\n          test -f docker-compose.yml\n          test -f .env.example\n          test -d k8s\n          test -d helm\n          test -d terraform\n      - uses: docker/login-action@v3\n        with:\n          registry: ghcr.io\n          username: ${{{{ github.actor }}}}\n          password: ${{{{ secrets.GITHUB_TOKEN }}}}\n      - name: Image publishing placeholder\n        run: echo \"Starter project validated. Add application source before building {image}.\"\n      - name: Update GitOps repo\n        run: echo \"update opsforge-gitops image tag\"\n"},
        {"file_name": "application.yaml", "file_path": "argocd/application.yaml", "file_type": "argocd", "content": f"apiVersion: argoproj.io/v1alpha1\nkind: Application\nmetadata:\n  name: {app_name}-{project.environment.value}\n  namespace: {settings.ARGOCD_NAMESPACE}\nspec:\n  project: default\n  source:\n    repoURL: https://github.com/{owner}/{settings.GITHUB_GITOPS_REPO}.git\n    targetRevision: main\n    path: apps/{app_name}/{project.environment.value}\n  destination:\n    server: https://kubernetes.default.svc\n    namespace: {namespace}\n  syncPolicy:\n    automated:\n      prune: true\n      selfHeal: true\n"},
        {"file_name": "main.tf", "file_path": "terraform/main.tf", "file_type": "terraform", "content": "resource \"aws_instance\" \"k3s\" {\n  ami           = var.ami_id\n  instance_type = var.instance_type\n  subnet_id     = var.subnet_id\n  key_name      = var.key_pair_name\n}\n"},
        {"file_name": "variables.tf", "file_path": "terraform/variables.tf", "file_type": "terraform", "content": "variable \"aws_region\" { default = \"replace-with-aws-region\" }\nvariable \"ami_id\" { default = \"replace-with-ami-id\" }\nvariable \"instance_type\" { default = \"replace-with-instance-type\" }\nvariable \"key_pair_name\" { default = \"replace-with-key-pair-name\" }\nvariable \"vpc_id\" { default = \"replace-with-vpc-id\" }\nvariable \"subnet_id\" { default = \"replace-with-subnet-id\" }\n"},
        {"file_name": "outputs.tf", "file_path": "terraform/outputs.tf", "file_type": "terraform", "content": "output \"k3s_public_ip\" { value = aws_instance.k3s.public_ip }\n"},
        {"file_name": "providers.tf", "file_path": "terraform/providers.tf", "file_type": "terraform", "content": "provider \"aws\" {\n  region = var.aws_region\n}\n"},
        {"file_name": "README.md", "file_path": "README.md", "file_type": "docs", "content": f"# {app_name}\n\nGenerated by OpsForge for React + FastAPI + PostgreSQL + Redis.\n\nImage: `{image}`\n\nSecrets are placeholders and must be configured securely before production deployment.\n"},
    ]


def generate_files(db: Session, project: Project, github_username: str | None = None) -> list[GeneratedFile]:
    db.execute(delete(GeneratedFile).where(GeneratedFile.project_id == project.id))
    files = [
        GeneratedFile(project_id=project.id, **file_spec)
        for file_spec in build_files(project, github_username)
    ]
    db.add_all(files)
    db.flush()
    return files
