apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-access
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/BIRAJ49/OpsForge.git
    targetRevision: main
    path: deploy/k8s/platform-access
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
