apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- rbac.yaml
- postgres.yaml
- redis.yaml
- backend.yaml
- frontend.yaml
- ingress.yaml
- sealed-secret.yaml

images:
- name: ghcr.io/biraj49/opsforge-backend
  newName: ghcr.io/biraj49/opsforge-backend
  newTag: e6278a50f71d1658b884851a2d29b77aeb4c7ce7
- name: ghcr.io/biraj49/opsforge-frontend
  newName: ghcr.io/biraj49/opsforge-frontend
  newTag: e6278a50f71d1658b884851a2d29b77aeb4c7ce7
