apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- rbac.yaml
- postgres.yaml
- redis.yaml
- backend.yaml
- frontend.yaml
- ingress.yaml
- sealed-secret.yaml

images:
- name: ghcr.io/biraj49/opsforge-backend
  newName: ghcr.io/biraj49/opsforge-backend
  newTag: 852d0aca8a6b1557d90fe325950df6574ac5d9cc
- name: ghcr.io/biraj49/opsforge-frontend
  newName: ghcr.io/biraj49/opsforge-frontend
  newTag: 852d0aca8a6b1557d90fe325950df6574ac5d9cc
