apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- rbac.yaml
- postgres.yaml
- redis.yaml
- backend.yaml
- frontend.yaml
- ingress.yaml
- sealed-secret.yaml

images:
- name: ghcr.io/biraj49/opsforge-backend
  newName: ghcr.io/biraj49/opsforge-backend
  newTag: 30ce5398fe0992f1dd87b789f164effd2c51ede1
- name: ghcr.io/biraj49/opsforge-frontend
  newName: ghcr.io/biraj49/opsforge-frontend
  newTag: 30ce5398fe0992f1dd87b789f164effd2c51ede1
