import { api } from '../services/api'

export const PROJECT_TYPES = [
  'Docker',
  'Kubernetes',
  'CI/CD',
  'Terraform',
  'AWS Deployment',
  'Monitoring',
  'Self-Healing DevOps',
]

export const DIFFICULTIES = ['Beginner', 'Intermediate', 'Advanced']

const PROJECTS_KEY = 'opsforge_generated_projects'
const GUEST_COUNT_KEY = 'opsforge_guest_generation_count'
const GUEST_ID_KEY = 'opsforge_guest_id'

export function getGuestId() {
  let guestId = localStorage.getItem(GUEST_ID_KEY)
  if (!guestId) {
    guestId = crypto.randomUUID()
    localStorage.setItem(GUEST_ID_KEY, guestId)
  }
  return guestId
}

export function getGuestCount() {
  return Number(localStorage.getItem(GUEST_COUNT_KEY) || 0)
}

export function incrementGuestCount() {
  const next = getGuestCount() + 1
  localStorage.setItem(GUEST_COUNT_KEY, String(next))
  return next
}

export function guestLimitReached() {
  return getGuestCount() >= 3
}

export function getProjects() {
  try {
    return JSON.parse(localStorage.getItem(PROJECTS_KEY) || '[]')
  } catch {
    return []
  }
}

export function saveProject(project) {
  const projects = getProjects()
  const existingIndex = projects.findIndex((item) => item.id === project.id)
  if (existingIndex >= 0) {
    projects[existingIndex] = project
  } else {
    projects.unshift(project)
  }
  localStorage.setItem(PROJECTS_KEY, JSON.stringify(projects))
  return project
}

export function deleteProject(projectId) {
  localStorage.setItem(PROJECTS_KEY, JSON.stringify(getProjects().filter((project) => project.id !== projectId)))
}

export function projectsForUser(user) {
  return getProjects().filter((project) => {
    if (!user) return project.owner === 'guest'
    return project.owner === user.email
  })
}

function fileSet(projectType, title) {
  const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
  const base = {
    'README.md': `# ${title}\n\nGenerated by OpsForge.\n\n## Goal\nDeploy a production-style ${projectType} project with secure defaults.\n`,
  }

  const files = { ...base }
  if (['Docker', 'Kubernetes', 'Self-Healing DevOps'].includes(projectType)) {
    files.Dockerfile = 'FROM python:3.12-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install -r requirements.txt\nCOPY . .\nCMD ["uvicorn", "app.main:app", "--host", "0.0.0.0"]\n'
    files['docker-compose.yml'] = 'services:\n  app:\n    build: .\n    ports:\n      - "8000:8000"\n  redis:\n    image: redis:7-alpine\n'
  }
  if (['Kubernetes', 'Monitoring', 'Self-Healing DevOps'].includes(projectType)) {
    files['deployment.yaml'] = `apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: ${slug}\nspec:\n  replicas: 2\n  selector:\n    matchLabels:\n      app: ${slug}\n  template:\n    metadata:\n      labels:\n        app: ${slug}\n    spec:\n      containers:\n        - name: app\n          image: ghcr.io/BIRAJ49/${slug}:latest\n`
    files['service.yaml'] = `apiVersion: v1\nkind: Service\nmetadata:\n  name: ${slug}\nspec:\n  selector:\n    app: ${slug}\n  ports:\n    - port: 80\n      targetPort: 8000\n`
    files['ingress.yaml'] = `apiVersion: networking.k8s.io/v1\nkind: Ingress\nmetadata:\n  name: ${slug}\nspec:\n  ingressClassName: nginx\n`
  }
  if (['Terraform', 'AWS Deployment'].includes(projectType)) {
    files['main.tf'] = 'resource "aws_instance" "app" {\n  ami           = var.ami_id\n  instance_type = var.instance_type\n  subnet_id     = var.subnet_id\n}\n'
    files['variables.tf'] = 'variable "ami_id" { default = "replace-with-ami-id" }\nvariable "instance_type" { default = "replace-with-instance-type" }\nvariable "subnet_id" { default = "replace-with-subnet-id" }\n'
  }
  if (['CI/CD', 'Kubernetes', 'Self-Healing DevOps'].includes(projectType)) {
    files['.github/workflows/deploy.yml'] = 'name: Deploy\non:\n  push:\n    branches: [main]\njobs:\n  deploy:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: echo "Build, scan, push, update GitOps"\n'
  }
  return files
}

export function generateProject({ projectType, difficulty, requirement, user }) {
  const title = `${difficulty} ${projectType} Project`
  const toolsByType = {
    Docker: ['Docker', 'Docker Compose', 'Makefile'],
    Kubernetes: ['Docker', 'Kubernetes', 'kubectl', 'NGINX Ingress'],
    'CI/CD': ['GitHub Actions', 'GHCR', 'Trivy'],
    Terraform: ['Terraform', 'AWS provider', 'remote state placeholder'],
    'AWS Deployment': ['AWS EC2', 'Security Groups', 'IAM', 'K3s'],
    Monitoring: ['Prometheus-ready metrics', 'Grafana-ready dashboard', 'Alert rules'],
    'Self-Healing DevOps': ['Kubernetes probes', 'HPA', 'rollback workflow', 'incident rules'],
  }
  const files = fileSet(projectType, title)

  return {
    id: crypto.randomUUID(),
    owner: user?.email || 'guest',
    title,
    projectType,
    difficulty,
    requirement: requirement || 'No custom requirement provided.',
    overview: `A ${difficulty.toLowerCase()} level ${projectType} project plan with implementation steps, starter code, secure placeholders, and download-ready files.`,
    architecture: `The architecture separates source code, infrastructure manifests, CI/CD automation, and operational runbooks. Secrets are represented as placeholders and must be injected securely at deploy time.`,
    tools: toolsByType[projectType] || ['Docker', 'GitHub Actions'],
    steps: [
      'Create the repository and baseline folder structure.',
      'Add application runtime and configuration placeholders.',
      'Generate infrastructure and deployment files for the selected project type.',
      'Add validation, security scanning, and deployment workflow steps.',
      'Run locally, review generated files, then deploy through GitOps or CI/CD.',
    ],
    folderStructure: ['app/', 'infra/', 'k8s/', '.github/workflows/', 'README.md'],
    files,
    downloads: { zip: 0, pdf: 0 },
    createdAt: new Date().toISOString(),
  }
}

function downloadBlob(blob, fileName) {
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = fileName
  link.click()
  URL.revokeObjectURL(url)
}

async function downloadBackendProject(project, format) {
  const backendProjectId = project.backendProjectId || project.backendId
  if (!backendProjectId) return false
  const response = await api.get(`/projects/${backendProjectId}/download/${format}`, { responseType: 'blob' })
  downloadBlob(response.data, `${project.title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.${format}`)
  return true
}

export async function downloadProject(project, format) {
  try {
    if (await downloadBackendProject(project, format)) {
      const updated = { ...project, downloads: { ...project.downloads, [format]: (project.downloads?.[format] || 0) + 1 } }
      saveProject(updated)
      return updated
    }
  } catch {
    // Fall back to the local project export if the backend is unavailable.
  }
  const body = [
    project.title,
    '',
    project.overview,
    '',
    'Architecture:',
    project.architecture,
    '',
    'Tools:',
    ...project.tools.map((tool) => `- ${tool}`),
    '',
    'Steps:',
    ...project.steps.map((step, index) => `${index + 1}. ${step}`),
    '',
    ...Object.entries(project.files).flatMap(([fileName, content]) => [`--- ${fileName} ---`, content, '']),
  ].join('\n')
  const blob = new Blob([body], { type: format === 'pdf' ? 'application/pdf' : 'application/zip' })
  downloadBlob(blob, `${project.title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.${format}`)
  const updated = { ...project, downloads: { ...project.downloads, [format]: (project.downloads?.[format] || 0) + 1 } }
  saveProject(updated)
  return updated
}
